/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package data_mustahik;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
/**
 *
 * @author betawi
 */
public class DataMustahik extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DataMustahik.class.getName());

    public void tampilData() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("Alamat");
    model.addColumn("No HP");
    model.addColumn("Jenis Bantuan");
    model.addColumn("Tanggal Bantuan");
    model.addColumn("Status");

    try {

        Connection conn = koneksi.getConnection();

        String sql = "SELECT * FROM mustahik";

        Statement st = conn.createStatement();

        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getString("id_mustahik"),
                rs.getString("nama"),
                rs.getString("alamat"),
                rs.getString("no_hp"),
                rs.getString("jenis_bantuan"),
                rs.getString("tanggal_bantuan"),
                rs.getString("status")

            });

        }

        jTable1.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal menampilkan data : "
                + e.getMessage()
        );

    }
}
    /**
     * Creates new form DataMustahik
     */
    public DataMustahik() {
        initComponents();

        tampilData();

    jButton1.addActionListener(this::jButton1ActionPerformed);
    jButton2.addActionListener(this::jButton2ActionPerformed);
    jButton3.addActionListener(this::jButton3ActionPerformed);
}
    public DataMustahik(String level) {

    initComponents();

    this.level = level;

    tampilData();

    hakAkses();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Mustahik");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Input Data Baru");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Edit Data");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Hapus Data");

        jButton4.setText("Refresh");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Kembali");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButtonCetak.setText("Cetak");
        jButtonCetak.addActionListener(this::jButtonCetakActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 439, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(115, 115, 115)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCetak)
                                .addGap(30, 30, 30))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton5)
                            .addComponent(jButtonCetak))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButton4)
                .addGap(10, 10, 10)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_jButton4ActionPerformed

    private String level;
    
    private void hakAkses() {

    if(level.equalsIgnoreCase("user")) {

        jButton3.setVisible(false); // tombol Hapus Data

    }

}
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    int baris = jTable1.getSelectedRow();

    if (baris == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Pilih data yang akan diedit!"
        );

        return;
    }

    String id =
            jTable1.getValueAt(baris, 0).toString();

    EditData form = 
            new EditData(id);

    form.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new InputData().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Dashboard dashboardAdmin = new Dashboard();
                  dashboardAdmin.setVisible(true);
                  
        this.dispose();
    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        // TODO add your handling code here:
                                                 
    try {
        // 1. Membuat struktur dasar halaman HTML dan CSS agar tabelnya rapi
        String html = "<html>"
                + "<head>"
                + "<title>Laporan Data Mustahik</title>"
                + "<style>"
                + "body{font-family:Arial, sans-serif; padding:20px;}"
                + "table{border-collapse:collapse; width:100%; margin-top:20px;}"
                + "th,td{border:1px solid black; padding:10px; text-align:left;}"
                + "th{background:#cccccc; text-align:center;}"
                + "</style>"
                + "</head>"
                + "<body>";
        
        // 2. Membuat judul laporan utama
        html += "<h2 align='center'>LAPORAN DATA MUSTAHIK - SIMBA</h2>";
        html += "<table>";
        
        // 3. Membuat Header Kolom (Disesuaikan dengan tabel Mustahik kamu)
        html += "<tr>"
                + "<th>ID</th>"
                + "<th>Nama Mustahik</th>"
                + "<th>Alamat</th>"
                + "<th>No HP</th>"
                + "<th>Jenis Bantuan</th>"
                + "<th>Tanggal Bantuan</th>"
                + "<th>Status</th>"
                + "</tr>";
        
        // 4. Perulangan untuk mengambil semua data dari JTable secara otomatis
        // PASTIKAN 'jTable1' di bawah ini diganti dengan nama variabel tabelmu (misal: tblMustahik jika diganti)
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            html += "<tr>";
            for (int j = 0; j < jTable1.getColumnCount(); j++) {
                html += "<td>"
                        + jTable1.getValueAt(i, j)
                        + "</td>";
            }
            html += "</tr>";
        }
        
        html += "</table>";
        html += "</body></html>";
        
        // 5. Menyimpan teks HTML menjadi file fisik di komputer kamu
        java.io.File file = new java.io.File("laporan_mustahik.html");
        java.io.FileWriter fw = new java.io.FileWriter(file);
        fw.write(html);
        fw.close();
        
        // 6. Membuka file HTML tersebut secara otomatis ke Browser default komputer
        java.awt.Desktop.getDesktop().browse(file.toURI());
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal membuat laporan: " + e.getMessage());
    }

    }//GEN-LAST:event_jButtonCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void jButton3ActionPerformed(ActionEvent evt) {

    int baris = jTable1.getSelectedRow();

    if (baris == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Pilih data yang akan dihapus!"
        );

        return;
    }

    String id =
            jTable1.getValueAt(baris, 0).toString();

    int konfirmasi =
            JOptionPane.showConfirmDialog(
                    this,
                    "Yakin ingin menghapus data?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {

        try {

            Connection conn =
                    koneksi.getConnection();

            String sql =
                    "DELETE FROM mustahik WHERE id_mustahik=?";

            PreparedStatement pst =
                    conn.prepareStatement(sql);

            pst.setString(1, id);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(
                    this,
                    "Data berhasil dihapus"
            );

            tampilData();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Gagal menghapus data : "
                    + e.getMessage()
            );

        }
    }
}
    
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DataMustahik().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
